import { defineConfig, presetIcons, presetTypography, presetWind4, transformerVariantGroup } from "unocss";

export default defineConfig({
  presets: [
    // The interactive design baseline relies on the browser's native
    // heading/list defaults where Akari does not override them. Wind's reset
    // zeroes those defaults (notably heading weights),
    // which makes the same CSS render with visibly thinner typography in the
    // Halo build. Keep Wind utilities and theme variables, but do not inject
    // the reset layer.
    presetWind4({ preflights: { reset: false } }),
    presetTypography(),
    presetIcons({
      scale: 1.1,
      warn: true,
      extraProperties: {
        display: "inline-block",
        "vertical-align": "middle",
      },
    }),
  ],
  transformers: [transformerVariantGroup()],
  shortcuts: {
    "ak-shell": "mx-auto w-[min(1180px,calc(100%-32px))] md:w-[min(1180px,calc(100%-48px))]",
    "ak-button":
      "inline-flex min-h-11 items-center justify-center gap-2 rounded-full px-5 text-sm font-700 transition duration-200 focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[var(--accent)]",
    "ak-icon-button":
      "inline-grid size-11 place-items-center rounded-full border border-[var(--line)] bg-[var(--surface)] text-[var(--ink)] transition duration-200 hover:-translate-y-0.5 hover:border-[var(--accent-soft)] hover:text-[var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[var(--accent)]",
    "ak-kicker": "text-[11px] font-800 tracking-[0.22em] text-[var(--accent)] uppercase",
    "ak-title": "font-[var(--font-display)] text-[clamp(2rem,5vw,4.5rem)] font-800 leading-[1.04] tracking-[-0.04em]",
  },
  safelist: [
    "ak-shell",
    "ak-button",
    "ak-icon-button",
    "ak-kicker",
    "ak-title",
    "i-lucide-house",
    "i-lucide-grid-2x2",
    "i-lucide-book-open-text",
    "i-lucide-images",
    "i-lucide-sparkles",
    "i-lucide-user-round",
    "i-lucide-search",
    "i-lucide-moon",
    "i-lucide-sun",
    "i-lucide-menu",
    "i-lucide-x",
    "i-lucide-arrow-right",
    "i-lucide-arrow-up-right",
    "i-lucide-calendar-days",
    "i-lucide-cloud-sun",
    "i-lucide-sunset",
    "i-lucide-train-front",
    "i-lucide-layout-grid",
    "i-lucide-clock-3",
    "i-lucide-message-circle",
    "i-lucide-heart",
    "i-lucide-headphones",
    "i-lucide-play",
    "i-lucide-pause",
    "i-lucide-flower-2",
    "i-lucide-tags",
    "i-lucide-archive",
    "i-lucide-disc-3",
    "i-lucide-users-round",
    "i-lucide-chevron-down",
    "i-lucide-external-link",
    "i-lucide-camera",
    "i-lucide-volume-2",
    "i-lucide-film",
    "i-lucide-library",
    "i-lucide-list-music",
    "i-lucide-rss",
    "i-lucide-copy",
    "i-lucide-check",
    "i-lucide-loader-circle",
    "i-lucide-circle-alert",
    "i-lucide-arrow-left",
    "i-lucide-arrow-down",
    "i-lucide-audio-lines",
    "i-lucide-book-dashed",
    "i-lucide-book-open",
    "i-lucide-chevron-left",
    "i-lucide-chevron-right",
    "i-lucide-clapperboard",
    "i-lucide-cloud-rain",
    "i-lucide-cloud-off",
    "i-lucide-coffee",
    "i-lucide-eye",
    "i-lucide-folder-heart",
    "i-lucide-image-off",
    "i-lucide-keyboard",
    "i-lucide-lamp-wall-up",
    "i-lucide-message-circle-off",
    "i-lucide-message-circle-heart",
    "i-lucide-mail-open",
    "i-lucide-mail-plus",
    "i-lucide-notebook-tabs",
    "i-lucide-pencil-line",
    "i-lucide-pen-line",
    "i-lucide-pin",
    "i-lucide-plus",
    "i-lucide-refresh-cw",
    "i-lucide-search-x",
    "i-lucide-send",
    "i-lucide-shield-check",
    "i-lucide-snowflake",
    "i-lucide-sticky-note",
    "i-lucide-wind",
  ],
});
